// 分类数据
var pro1=[
    {
      name:"浏览足迹",
      imga:require("../assets/classify-img/qing.png"),
      text:"清空",
      pro:[
        {
          proname:"图书专区",
          img:require("../assets/classify-img/01.jpg")
        },
         {
          proname:"米面调料",
          img:require("../assets/classify-img/09.jpg")
        },
      ]
    },
     {
      name:"618大促",
      text:"",
      imga:require("../assets/classify-img/26.png"),
      pro:[
        {
          proname:"尖货手机",
          img:require("../assets/classify-img/11.png")
        },
         {
          proname:"潮流小电",
          img:require("../assets/classify-img/12.png")
        },
         {
          proname:"超嗨预售",
          img:require("../assets/classify-img/13.jpg")
        },
         {
          proname:"5G盛典",
          img:require("../assets/classify-img/14.jpg")
        },
         {
          proname:"健康爆款",
          img:require("../assets/classify-img/15.jpg")
        },
         {
          proname:"空调",
          img:require("../assets/classify-img/16.jpg")
        },
      ]
    },
    {
      name:"热门分类",
      text:"排行榜>",
      imga:require("../assets/classify-img/08.png"),
      pro:[
        {
          proname:"5G",
          img:require("../assets/classify-img/17.jpg")
        },
         {
          proname:"电脑",
          img:require("../assets/classify-img/18.png")
        },
         {
          proname:"全面屏手机",
          img:require("../assets/classify-img/19.jpg")
        },
         {
          proname:"保健品",
          img:require("../assets/classify-img/20.jpg")
        },
         {
          proname:"口罩",
          img:require("../assets/classify-img/21.jpg")
        },
         {
          proname:"驱蚊用品",
          img:require("../assets/classify-img/22.jpg")
        },
         {
          proname:"电磁炉",
          img:require("../assets/classify-img/23.jpg")
        }, 
        {
          proname:"电热水壶",
          img:require("../assets/classify-img/24.jpg")
        },
         {
          proname:"数据线",
          img:require("../assets/classify-img/25.jpg")
        }, 
        {
          proname:"图书",
          img:require("../assets/classify-img/01.jpg")
        }, 
        {
          proname:"美妆护肤",
          img:require("../assets/classify-img/27.jpg")
        }, 
        {
          proname:"除菌液",
          img:require("../assets/classify-img/28.jpg")
        },
         {
          proname:"休闲零食",
          img:require("../assets/classify-img/29.jpg")
        },
         {
          proname:"充电宝",
          img:require("../assets/classify-img/30.jpg")
        },
         {
          proname:"游戏手机",
          img:require("../assets/classify-img/31.jpg")
        },
         {
          proname:"温度计",
          img:require("../assets/classify-img/32.jpg")
        },
         {
          proname:"摄影机",
          img:require("../assets/classify-img/33.jpg")
        },
         {
          proname:"游戏机",
          img:require("../assets/classify-img/34.jpg")
        },
      ]
    },
  ]
var pro2=[
  {
    name:"热门品牌",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"小米",
        img:require("../assets/classify-img/35.png")
      },
       {
        proname:"华为",
        img:require("../assets/classify-img/36.jpg")
      },
      {
        proname:"荣耀",
        img:require("../assets/classify-img/37.jpg")
      },
      {
        proname:"iphone",
        img:require("../assets/classify-img/38.jpg")
      },
      {
        proname:"vivo",
        img:require("../assets/classify-img/39.png")
      },
      {
        proname:"OPPO",
        img:require("../assets/classify-img/40.png")
      },
      {
        proname:"魅族",
        img:require("../assets/classify-img/41.jpg")
      },
      {
        proname:"三星",
        img:require("../assets/classify-img/42.png")
      },
      {
        proname:"一加",
        img:require("../assets/classify-img/43.jpg")
      },
      {
        proname:"360手机",
        img:require("../assets/classify-img/44.jpg")
      },
      {
        proname:"锤子手机",
        img:require("../assets/classify-img/45.jpg")
      },
      {
        proname:"努比亚",
        img:require("../assets/classify-img/46.jpg")
      },
    ]
  },
   {
    name:"手机通信",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"老人机",
        img:require("../assets/classify-img/47.jpg")
      },
       {
        proname:"手机",
        img:require("../assets/classify-img/48.jpg")
      },
       {
        proname:"全面屏手机",
        img:require("../assets/classify-img/49.jpg")
      },
       {
        proname:"游戏手机",
        img:require("../assets/classify-img/50.jpg")
      },
       {
        proname:"拍照手机",
        img:require("../assets/classify-img/51.jpg")
      },
       {
        proname:"对讲机",
        img:require("../assets/classify-img/52.jpg")
      },
      {
        proname:"京东回收",
        img:require("../assets/classify-img/53.jpg")
      },
      {
        proname:"女性手机",
        img:require("../assets/classify-img/54.jpg")
      },
      {
        proname:"京东维修",
        img:require("../assets/classify-img/55.jpg")
      },
    ]
  },
  {
    name:"运营商",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"合约机",
        img:require("../assets/classify-img/56.png")
      },
       {
        proname:"选号卡",
        img:require("../assets/classify-img/57.png")
      },
       {
        proname:"办套餐",
        img:require("../assets/classify-img/58.jpg")
      },
       {
        proname:"京东网厅",
        img:require("../assets/classify-img/59.jpg")
      },
    ]
  },
  {
    name:"手机配件",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"数据线",
        img:require("../assets/classify-img/60.jpg")
      },
       {
        proname:"手机储蓄卡",
        img:require("../assets/classify-img/61.jpg")
      },
       {
        proname:"充电宝",
        img:require("../assets/classify-img/62.jpg")
      },
    ]
  },
]
export {pro1,pro2}