// 分类数据
var pro1=[
    {
      name:"浏览足迹",
      imga:require("../assets/classify-img/qing.png"),
      text:"清空",
      pro:[
        {
          proname:"图书专区",
          img:require("../assets/classify-img/01.jpg")
        },
         {
          proname:"米面调料",
          img:require("../assets/classify-img/09.jpg")
        },
      ]
    },
     {
      name:"618大促",
      text:"",
      imga:require("../assets/classify-img/26.png"),
      pro:[
        {
          proname:"尖货手机",
          img:require("../assets/classify-img/11.png")
        },
         {
          proname:"潮流小电",
          img:require("../assets/classify-img/12.png")
        },
         {
          proname:"超嗨预售",
          img:require("../assets/classify-img/13.jpg")
        },
         {
          proname:"5G盛典",
          img:require("../assets/classify-img/14.jpg")
        },
         {
          proname:"健康爆款",
          img:require("../assets/classify-img/15.jpg")
        },
         {
          proname:"空调",
          img:require("../assets/classify-img/16.jpg")
        },
      ]
    },
    {
      name:"热门分类",
      text:"排行榜>",
      imga:require("../assets/classify-img/08.png"),
      pro:[
        {
          proname:"5G",
          img:require("../assets/classify-img/17.jpg")
        },
         {
          proname:"电脑",
          img:require("../assets/classify-img/18.png")
        },
         {
          proname:"全面屏手机",
          img:require("../assets/classify-img/19.jpg")
        },
         {
          proname:"保健品",
          img:require("../assets/classify-img/20.jpg")
        },
         {
          proname:"口罩",
          img:require("../assets/classify-img/21.jpg")
        },
         {
          proname:"驱蚊用品",
          img:require("../assets/classify-img/22.jpg")
        },
         {
          proname:"电磁炉",
          img:require("../assets/classify-img/23.jpg")
        }, 
        {
          proname:"电热水壶",
          img:require("../assets/classify-img/24.jpg")
        },
         {
          proname:"数据线",
          img:require("../assets/classify-img/25.jpg")
        }, 
        {
          proname:"图书",
          img:require("../assets/classify-img/01.jpg")
        }, 
        {
          proname:"美妆护肤",
          img:require("../assets/classify-img/27.jpg")
        }, 
        {
          proname:"除菌液",
          img:require("../assets/classify-img/28.jpg")
        },
         {
          proname:"休闲零食",
          img:require("../assets/classify-img/29.jpg")
        },
         {
          proname:"充电宝",
          img:require("../assets/classify-img/30.jpg")
        },
         {
          proname:"游戏手机",
          img:require("../assets/classify-img/31.jpg")
        },
         {
          proname:"温度计",
          img:require("../assets/classify-img/32.jpg")
        },
         {
          proname:"摄影机",
          img:require("../assets/classify-img/33.jpg")
        },
         {
          proname:"游戏机",
          img:require("../assets/classify-img/34.jpg")
        },
      ]
    },
  ]


var pro2=[
  {
    name:"热门品牌",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"小米",
        img:require("../assets/classify-img/35.png")
      },
       {
        proname:"华为",
        img:require("../assets/classify-img/36.jpg")
      },
      {
        proname:"荣耀",
        img:require("../assets/classify-img/37.jpg")
      },
      {
        proname:"iphone",
        img:require("../assets/classify-img/38.jpg")
      },
      {
        proname:"vivo",
        img:require("../assets/classify-img/39.png")
      },
      {
        proname:"OPPO",
        img:require("../assets/classify-img/40.png")
      },
      {
        proname:"魅族",
        img:require("../assets/classify-img/41.jpg")
      },
      {
        proname:"三星",
        img:require("../assets/classify-img/42.png")
      },
      {
        proname:"一加",
        img:require("../assets/classify-img/43.jpg")
      },
      {
        proname:"360手机",
        img:require("../assets/classify-img/44.jpg")
      },
      {
        proname:"锤子手机",
        img:require("../assets/classify-img/45.jpg")
      },
      {
        proname:"努比亚",
        img:require("../assets/classify-img/46.jpg")
      },
    ]
  },
   {
    name:"手机通信",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"老人机",
        img:require("../assets/classify-img/47.jpg")
      },
       {
        proname:"手机",
        img:require("../assets/classify-img/48.jpg")
      },
       {
        proname:"全面屏手机",
        img:require("../assets/classify-img/49.jpg")
      },
       {
        proname:"游戏手机",
        img:require("../assets/classify-img/50.jpg")
      },
       {
        proname:"拍照手机",
        img:require("../assets/classify-img/51.jpg")
      },
       {
        proname:"对讲机",
        img:require("../assets/classify-img/52.jpg")
      },
      {
        proname:"京东回收",
        img:require("../assets/classify-img/53.jpg")
      },
      {
        proname:"女性手机",
        img:require("../assets/classify-img/54.jpg")
      },
      {
        proname:"京东维修",
        img:require("../assets/classify-img/55.jpg")
      },
    ]
  },
  {
    name:"运营商",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"合约机",
        img:require("../assets/classify-img/56.png")
      },
       {
        proname:"选号卡",
        img:require("../assets/classify-img/57.png")
      },
       {
        proname:"办套餐",
        img:require("../assets/classify-img/58.jpg")
      },
       {
        proname:"京东网厅",
        img:require("../assets/classify-img/59.jpg")
      },
    ]
  },
  {
    name:"手机配件",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"数据线",
        img:require("../assets/classify-img/60.jpg")
      },
       {
        proname:"手机储蓄卡",
        img:require("../assets/classify-img/61.jpg")
      },
       {
        proname:"充电宝",
        img:require("../assets/classify-img/62.jpg")
      },
    ]
  },
]


var pro3=[
  {
    name:"热卖分类",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"轻薄本",
        img:require("../assets/classify-img/63.png")
      },
       {
        proname:"游戏本",
        img:require("../assets/classify-img/64.png")
      },
      {
        proname:"机械键盘",
        img:require("../assets/classify-img/65.jpg")
      },
      {
        proname:"组装电脑",
        img:require("../assets/classify-img/66.jpg")
      },
      {
        proname:"移动硬盘",
        img:require("../assets/classify-img/67.jpg")
      },
      {
        proname:"显卡",
        img:require("../assets/classify-img/68.jpg")
      },
      {
        proname:"游戏机台式",
        img:require("../assets/classify-img/69.jpg")
      },
      {
        proname:"家用打印机",
        img:require("../assets/classify-img/70.jpg")
      },
      {
        proname:"吃鸡装备",
        img:require("../assets/classify-img/71.jpg")
      },
      {
        proname:"曲屏显示器",
        img:require("../assets/classify-img/72.jpg")
      },
      {
        proname:"投影机",
        img:require("../assets/classify-img/73.jpg")
      },
      {
        proname:"日本文具",
        img:require("../assets/classify-img/74.jpg")
      },
    ]
  },
   {
    name:"电脑整机",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"笔记本",
        img:require("../assets/classify-img/75.jpg")
      },
       {
        proname:"平板电脑",
        img:require("../assets/classify-img/76.jpg")
      },
       {
        proname:"一体机",
        img:require("../assets/classify-img/77.jpg")
      },
      {
        proname:"台式机",
        img:require("../assets/classify-img/78.jpg")
      },
    ]
  },
]

var pro4=[
  {
    name:"厨房小电",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"电压力锅",
        img:require("../assets/classify-img/79.jpg")
      },
       {
        proname:"电水壶/热水壶",
        img:require("../assets/classify-img/80.jpg")
      },
      {
        proname:"电饭煲",
        img:require("../assets/classify-img/81.jpg")
      },
      {
        proname:"电磁炉",
        img:require("../assets/classify-img/82.jpg")
      },
      {
        proname:"微波炉",
        img:require("../assets/classify-img/83.jpg")
      },
      {
        proname:"电饼铛",
        img:require("../assets/classify-img/84.jpg")
      },
      {
        proname:"豆浆机",
        img:require("../assets/classify-img/85.jpg")
      },
      {
        proname:"多用途锅",
        img:require("../assets/classify-img/86.jpg")
      },
      {
        proname:"料理机",
        img:require("../assets/classify-img/87.jpg")
      },
      {
        proname:"榨汁机/原汁机",
        img:require("../assets/classify-img/88.jpg")
      },
    ]
  },
   {
    name:"个护健康",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"电吹风",
        img:require("../assets/classify-img/89.jpg")
      },
       {
        proname:"剃须刀",
        img:require("../assets/classify-img/90.jpg")
      },
       {
        proname:"理发器",
        img:require("../assets/classify-img/91.jpg")
      },
      {
        proname:"足浴盆",
        img:require("../assets/classify-img/92.jpg")
      },
    ]
  },
]

var pro5=[
  {
    name:"当季主推",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"防晒",
        img:require("../assets/classify-img/95.jpg")
      },
       {
        proname:"控油",
        img:require("../assets/classify-img/96.jpg")
      },
    ]
  },
   {
    name:"拔草推荐",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"明星同款面膜",
        img:require("../assets/classify-img/97.jpg")
      },
       {
        proname:"显白口红",
        img:require("../assets/classify-img/98.jpg")
      },
       {
        proname:"小美盒",
        img:require("../assets/classify-img/99.jpg")
      },
    ]
  },
  {
    name:"潮流速递",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"新品速递",
        img:require("../assets/classify-img/100.jpg")
      },
       {
        proname:"精选礼盒",
        img:require("../assets/classify-img/101.jpg")
      },
       {
        proname:"潮流风向",
        img:require("../assets/classify-img/102.jpg")
      },
    ]
  },
]

var pro6=[
  {
    name:"畅销推荐",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"个护馆",
        img:require("../assets/classify-img/103.jpg")
      },
       {
        proname:"清洁馆",
        img:require("../assets/classify-img/104.jpg")
      },
      {
        proname:"进口清洁",
        img:require("../assets/classify-img/105.jpg")
      },
      {
        proname:"卫生棉条",
        img:require("../assets/classify-img/106.jpg")
      },
      {
        proname:"厕纸",
        img:require("../assets/classify-img/107.jpg")
      },
      {
        proname:"花露水",
        img:require("../assets/classify-img/108.jpg")
      },
    ]
  },
   {
    name:"明星品牌",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"得宝",
        img:require("../assets/classify-img/109.jpg")
      },
       {
        proname:"施华蔻专业",
        img:require("../assets/classify-img/110.jpg")
      },
       {
        proname:"舒洁",
        img:require("../assets/classify-img/111.jpg")
      },
    ]
  },
]

var pro7=[
  {
    name:"热卖推荐",
    imga:require("../assets/classify-img/26.png"),
    text:"",
    pro:[
      {
        proname:"机油",
        img:require("../assets/classify-img/112.jpg")
      },
       {
        proname:"汽车坐垫",
        img:require("../assets/classify-img/113.jpg")
      },
      {
        proname:"汽车水枪",
        img:require("../assets/classify-img/114.jpg")
      },
      {
        proname:"行车记录仪",
        img:require("../assets/classify-img/115.jpg")
      },
      {
        proname:"轮胎",
        img:require("../assets/classify-img/116.jpg")
      },
      {
        proname:"应急救援",
        img:require("../assets/classify-img/117.png")
      },
    ]
  },
   {
    name:"乘用车",
    text:"",
    imga:require("../assets/classify-img/26.png"),
    pro:[
      {
        proname:"全部车型",
        img:require("../assets/classify-img/118.png")
      },
       {
        proname:"二手车",
        img:require("../assets/classify-img/119.png")
      },
       {
        proname:"选车攻略",
        img:require("../assets/classify-img/120.png")
      },
    ]
  },
]
export {pro1,pro2,pro3,pro4,pro5,pro6,pro7}